export { CreateApplication } from "./CreateApplication/CreateApplication";
export { StartPage } from "./StartPage/StartPage";
export { Auth } from "./Auth/Auth";
export { Registration } from "./Registration/Registration";
export { RestorePassPage } from "./RestorePassword/RestorePassPage";
export { MainPage } from "./Main/MainPage";
export { TemplatesPage } from "./Templates/TemplatesPage";
export { Profile } from "./Profile/Profile";
export { Payment } from "./Payment/Payment";
export * from "./ChangeProfile";
export * from "./CreateProject";
export * from "./NotFoundPage";
